project:
  type: book
  # change output-dir to "docs" to publish to gh pages
  output-dir: docs

book:
  title: "Open Science: Tools Applications, & Workflow"
  author: "Nic Jelinski"
  date: "11/13/2023"
  cover-image: "open-science-badge.png"
  
  chapters:
    - index.qmd
    - intro.qmd
    - part: project-setup.qmd
      chapters: 
        - para-system.qmd
        - project-subfolder-structure.qmd
        - writing-readmes.qmd
        - github-setup-workflow.qmd
        - integrating-zotero.qmd
    - part: pre-data-raw-data.qmd
      chapters:
      - field-projects.qmd
      - lab-projects.qmd
      - review-projects.qmd
      - data-synthesis-projects.qmd
    - part: data-munging.qmd
      chapters:
      - standardizing-formats.qmd
    - part: style-guides-and-standards.qmd
      chapters:
      - r-style-guide.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

