project:
  type: book
  # change output-dir to "docs" to publish to gh pages
  output-dir: docs

book:
  title: "Open Science: Tools Applications, & Workflow"
  author: "Nic Jelinski"
  date: "11/13/2023"
  cover-image: "open-science-badge.png"
  
  chapters:
    - index.qmd
    - 01-intro.qmd
    - part: 02-project-setup.qmd
      chapters: 
        - 02a-para-system.qmd
        - 02b-project-subfolder-structure.qmd
        - 02c-writing-readmes.qmd
        - 02d-github-setup-workflow.qmd
        - 02e-integrating-zotero.qmd
    - part: 03-pre-data-raw-data.qmd
      chapters:
      - 03a-field-projects.qmd
      - 03b-lab-projects.qmd
      - 03c-review-projects.qmd
      - 03d-data-synthesis-projects.qmd
    - part: 04-data-munging.qmd
      chapters:
      #- 04a-pulling-raw-data.qmd
      #- 04b-qaqc-data-cleaning.qmd #includes log, includes reps for lab data, flagging samples for rerun
      - 04c-standardizing-formats.qmd
    #- part: 05-data-analysis-interpretation.qmd #metadata
        #- 05a-data-analysis-log.qmd
        #- 05b-building-analysis-scripts.qmd
        #- 05c-maintaining-R-project.qmd
    #- part: 06-writing-external-products.qmd
        #- 06a-notetaking-strategies.qmd 
        #- 06b-on-writing.qmd
        #- 06c-writing-manuscripts.qmd
        #- 06d-writing-metadata.qmd #standards
        #- 06e-writing-in-markdown.qmd
    #- part: 07-publishing.qmd
        #- 07a-data-archiving-storage.qmd
        #- 07b-licenses-copyright.qmd
        #- 07c-formats-standards.qmd
        #- 07d-quarto-books.qmd
        #- 07e-orcid-google-scholar.qmd
    - part: 08-style-guides-and-standards.qmd
      chapters:
      - 08a-r-style-guide.qmd
      #- 08b-markdown-style-guide.qmd
      #- 08c-tabular-data-standards.qmd #csv, header names, data types, etc
    #- part: 09-open-source-resources.qmd
        #- 09a-other-references.qmd
        #- 09b-looking-at-future.qmd
    - 10-summary.qmd
    - 11-references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

