project:
  type: book
  # change output-dir to "docs" to publish to gh pages
  output-dir: docs

book:
  title: "Open Science: Tools Applications, & Workflow"
  author: "Nic Jelinski"
  date: "11/13/2023"
  cover-image: "open-science-badge.png"
  
  chapters:
    - index.qmd
    - 01-intro.qmd
    - part: 02-project-setup.qmd
      chapters: 
        - 02a-para-system.qmd
        - 02b-project-subfolder-structure.qmd
        - 02c-writing-readmes.qmd
        - 02d-github-setup-workflow.qmd
        - 02e-integrating-zotero.qmd
    - part: 03-pre-data-raw-data.qmd
      chapters:
      - 03a-field-projects.qmd
      - 03b-lab-projects.qmd
      - 03c-review-projects.qmd
      - 03d-data-synthesis-projects.qmd
    - part: 04-raw-data-qaqc.qmd
      # chapters:
      # - 04a-quality-assurance-plans.qmd
    - part: 05-data-munging.qmd
      chapters:
      - 05a-pulling-raw-data.qmd
      - 05b-qc-data-cleaning.qmd #includes log, includes reps for lab data, flagging samples for rerun
      - 05c-standardizing-formats.qmd
    #- part: 06-data-analysis-interpretation.qmd #metadata
        #- 06x-exploratory-data-analysis-log.qmd
        #- 06a-data-analysis-log.qmd
        #- 06b-building-analysis-scripts.qmd
        #- 06c-maintaining-R-project.qmd
    #- part: 07-writing-external-products.qmd
        #- 07a-notetaking-strategies.qmd 
        #- 07b-on-writing.qmd
        #- 07c-writing-manuscripts.qmd
        #- 07d-writing-metadata.qmd #standards
        #- 07e-writing-in-markdown.qmd
    #- part: 08-publishing.qmd
        #- 08a-data-archiving-storage.qmd
        #- 08b-licenses-copyright.qmd
        #- 08c-formats-standards.qmd
        #- 08d-quarto-books.qmd
        #- 08e-orcid-google-scholar.qmd
    - part: 09-style-guides-and-standards.qmd
      chapters:
      - 09a-r-style-guide.qmd
      #- 09b-markdown-style-guide.qmd
      #- 09c-tabular-data-standards.qmd #csv, header names, data types, etc
    #- part: 10-open-source-resources.qmd
        #- 10a-other-references.qmd
        #- 10b-looking-at-future.qmd
    - 11-summary.qmd
    - 12-references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

