# Field Projects

Field projects here as projects that require doing fieldwork to collect novel physical samples or morphological data. These projects require travel of some sort to collect raw data. Raw data for these projects typically will consist of physical samples.

## Pre-Data Infrastructure
### Survey123 for tabular data, spatial data, and image collection
Our standardized tool for data collection for field projects is [ArcGIS Survey123](https://survey123.arcgis.com/). Survey123 is a tool that allows you to create customized data entry and submission forms that you can then access through the Survey123 app on your phone. These forms can be created through the ArcGIS Online Survey123 portal. Although it is a proprietary tool, all faculty, students and staff at UMN have full, free access to the ArcGIS Online suite of tools which includes Survey123. Despite the fact that Survey123 is proprietary and not open source, it is highly functional and therefore the ease of use makes it our tool of choice. This chapter assumes you are familiar and have accessed Survey123. If you have not worked with Survey123 before, it is well supported and documented by ESRI and you can check out our Tools: Survey123 chapter #todo in this book.

### Lab Standards for Survey123 Form
As you set up your Survey123 form, you should think through each of the pieces of information that will be important to collect in the field and provide a way to capture that information in your form. When in doubt - err on the side of including it in your form - you can always ignore it in the field while using the app if there is some redundancy.

If you are doing a field project, you should strongly consider using Survey123 to collect your plot or site-level data. Think of what unit of your sampling will have a unqiue latitude and longitude and that is the data collection unit that your survey form should be designed for. For example, if you have a project that requires taking soil cores, with multiple samples from different depths taken from each core, then the survey form should be designed around each of the cores, which will have a unqiue latitude and longitude, and not each of the samples (many of which from the same core will have the same latitude and longitude).

Survey123 excels at consolidating spatial data (latitudes and longitudes), tabular data (text, numbers, or X entered in response to questions on the form), and images (taken in response to questions on the form) in one location. When you submit each of your records, this raw data will live in the Survey123 database through ArcGIS Online that is associated with your form.

Our laboratory standards for Survey123 forms is that they should (at a minimum) collect the following information:

- Name of initials of person recording data or submitting record
- GPS location of record (autocollected in response to location question)
- Date and time of record collection (autocollected in response to time question)
- Unique plot or observation number in the context of the project

Your Survey123 form should also include fields to enter all relevant raw data as required by your project.

### Additional Survey123 Functionality of Interest
*Images.* Survey123 is an excellent way to collect and organize images. Single image submission questions can be configured to collect multiple images. Once submitted, all images are stored with the associated record in the online database.

*Deep Customization - XLSForms* Deeper functionality for setting up forms in Survey123 requires a PC and the use of XLSForms and Survey123 Conect (a desktop app that only runs on Windows). While this is very annoying for us Mac users, it allows extensive customization of your Survey123 form, including but certainly not limited to:
    
- *Repeats*: "Repeats" allow you to generate multiple records (rows) from a single survey entry/submission - so for example, you can generate multiple rows for the master sample log (each row is a sample) from one submission form (plot or pedon): https://community.esri.com/t5/arcgis-survey123-blog/survey123-tricks-of-the-trade-repeats/ba-p/898041 
- *Customizing File Names for Submitted Images*: Customaization through XLS Forms allows you to set the file names of submitted photos - this is really important - automatically annotate photo file names with project, plot, and question or anything else from designated fields in the form (as well as date/time). This functionality can save significant time when you go to curate your photo archive. https://community.esri.com/t5/arcgis-survey123-blog/survey123-tricks-of-the-trade-set-the-file-name-of/ba-p/1217125

### Hard Copy Field Data Sheets
Survey123 is an excellent tool for collecting plot or site level data in the field with your phone. However, some types of field data collection are extremely difficult to digitize under field conditions. Examples of these are:

- Soil morphology data (lots of specialized acronyms, notes, and chicken scratches add depth to the data, often difficult to use phone while textureing soil, many fields and extremely time consuming to use an app or tablet in the field).
- Data consisting of many numbers or that exists at the sample level. Remember I said that Survey123 really shines when used at the level of unique geospatial coordinates which is typically the plot or site level. However, often times we may also be collecting data at the sample level. For example recording the dimensions of a permafrost soil core section that will go into a sample bag, or the field pH and EC of a soil sample. These data are best collected using hard copy forms. There are examples of hard copy forms for field data collection that Megan Andersen put together in the Jelinski Lab Field Handbook repository [here]#todo. **Always print your hard copy forms on Rite-In-The-Rain!!**

## Raw Data Collection
### Tips for using Survey 123 in the field


Images

Offline/Online

## Raw Data Curation

## Creating the Raw Data Archive

Should be generated within 2 weeks of retruning from the field

consists of: 
- shapefile in OGC Geopackage format containing lat lon and point or plot IDs
- tabular data exported from Survey123
- 

local + cloud (if fits local)

should contain pre-data - form spreadsheets, some way to export or archive the Survey123 form - what format?

NOTE: folder repo structure should contain a pre-data folder!!!!!

## Physical Sample Curation
sample numbers master sample sheet